# ------------------------------------------------------------
# Federico Alcerreca Treviño - A01281459
# Jaime Andres Montemayor Molina - A01176573
# ------------------------------------------------------------
import sys


# Declaracion de cubo semantico
class SemanticCube:
    def __init__(self):
        self.cube = {
            '+': {
                'int': {
                    'int': 'int',
                    'float': 'float',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'float',
                    'float': 'float',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            },
            '-': {
                'int': {
                    'int': 'int',
                    'float': 'float',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'float',
                    'float': 'float',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            },
            '/': {
                'int': {
                    'int': 'float',
                    'float': 'float',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'float',
                    'float': 'float',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            },
            '*': {
                'int': {
                    'int': 'int',
                    'float': 'float',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'float',
                    'float': 'float',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            },
            '>': {
                'int': {
                    'int': 'boolean',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'error',
                    'float': 'boolean',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            },
            '<': {
                'int': {
                    'int': 'boolean',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'error',
                    'float': 'boolean',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            },
            '<=': {
                'int': {
                    'int': 'boolean',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'error',
                    'float': 'boolean',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            },
            '>=': {
                'int': {
                    'int': 'boolean',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'error',
                    'float': 'boolean',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            },
            '==': {
                'int': {
                    'int': 'boolean',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'error',
                    'float': 'boolean',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'boolean',
                },
            },
            '!=': {
                'int': {
                    'int': 'boolean',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'error',
                    'float': 'boolean',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'boolean',
                },
            },
            '&&': {
                'int': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'boolean',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            },
            '||': {
                'int': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'float': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'string': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
                'boolean': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'boolean',
                    'char': 'error',
                },
                'char': {
                    'int': 'error',
                    'float': 'error',
                    'string': 'error',
                    'boolean': 'error',
                    'char': 'error',
                },
            }
        }
